baseURL = 'https://superare.cc/'
languageCode = 'en-us'
title = 'Superare Racing'
disableKinds = ['taxonomy', 'term']

[params]
  description = 'A Portland-based bike racing team looking to instill friendly competition, inclusion, and a love for bike racing.'
  tagline = 'Friendly competition, inclusion, and a love for bike racing.'

  [params.social]
    instagram = 'superare.cc'
    email = 'SuperareRacing@gmail.com'
